#############################################################################
# Makefile for building: cppserver
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  cppserver.pro
# Template: app
# Command: /home/local/Qt5.2.0/5.2.0/gcc_64/bin/qmake -o Makefile cppserver.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/local/Qt5.2.0/5.2.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf \
		cppserver.pro \
		cppserver.pro
QMAKE_TARGET  = cppserver
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = cppserver


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cppserver.pro /opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf \
		cppserver.pro
	$(QMAKE) -o Makefile cppserver.pro
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/unix.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/linux.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-base.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/qconfig.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/spec_post.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/default_post.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/yacc.prf:
/opt/Apps/local/Qt5.2.0/5.2.0/gcc_64/mkspecs/features/lex.prf:
cppserver.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile cppserver.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/cppserver1.0.0 || mkdir -p .tmp/cppserver1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cppserver1.0.0/ && (cd `dirname .tmp/cppserver1.0.0` && $(TAR) cppserver1.0.0.tar cppserver1.0.0 && $(COMPRESS) cppserver1.0.0.tar) && $(MOVE) `dirname .tmp/cppserver1.0.0`/cppserver1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cppserver1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

